name: Setup GNOME Runner + Tailscale + VNC + Apps

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-latest
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner
      TAILSCALE_HOSTNAME: gh-gnome-vnc-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Ensure runner user has sudo
        run: |
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}

      - name: Install GNOME + VNC server + Extra Apps
        run: |
          echo ">>> Installing GNOME Desktop + VNC..."
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
            gnome-session gnome-terminal nautilus xorg dbus-x11 \
            tigervnc-standalone-server tigervnc-common tigervnc-tools \
            qemu-system gnome-boxes virt-manager flatpak

          # Configure Snap (needed for apps like VS Code, Discord, Telegram)
          echo ">>> Setting up Snap..."
          sudo apt-get install -y snapd
          sudo systemctl enable --now snapd
          sudo ln -s /var/lib/snapd/snap /snap || true

          # Install apps via Snap
          echo ">>> Installing apps via Snap..."
          sudo snap install code --classic
          sudo snap install telegram-desktop
          sudo snap install discord

          # Setup Flatpak in user scope (to avoid system permission errors)
          echo ">>> Setting up Flatpak..."
          sudo -u ${USERNAME} flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || true

          # Configure VNC password for the runner
          mkdir -p /home/${USERNAME}/.vnc
          echo ${PASSWORD} | vncpasswd -f > /home/${USERNAME}/.vnc/passwd
          chmod 600 /home/${USERNAME}/.vnc/passwd
          chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.vnc

          # Start GNOME when VNC launches
          echo "gnome-session" > /home/${USERNAME}/.xsession
          chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.xsession

      - name: Install Tailscale
        run: |
          echo ">>> Installing Tailscale..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${TAILSCALE_HOSTNAME}"

      - name: Start VNC + Show Tailscale Info
        run: |
          echo ">>> Starting VNC server..."
          # Run VNC on all interfaces (not only localhost)
          sudo -u ${USERNAME} vncserver :1 -geometry 1280x800 -depth 24 -localhost no

          # Get Tailscale IP
          TAILSCALE_IP=$(tailscale ip -4 | head -n1)

          echo "=== CONNECTION INFO ==="
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo "Connect with any VNC client to:"
          echo "    ${TAILSCALE_IP}:5901"
          echo
          echo ">>> Keeping runner alive..."
          tail -f /dev/null
